export const DEFAULT_LOCATION_CONSUMER_GROUP = 'location-worker';
export const LOCATION_CONSUMER_ENABLED_ENV = 'KAFKA_LOCATION_CONSUMER_ENABLED';
export const LOCATION_CONSUMER_GROUP_ENV = 'KAFKA_LOCATION_CONSUMER_GROUP';
export const LOCATION_UPDATED_EVENT_TYPE = 'user.location.updated';
