export const LIVENESS_CHECK_QUEUE = 'liveness-check';
export const LIVENESS_CHECK_JOB_NAME = 'dispatch';
export const DEFAULT_LIVENESS_CHECK_INTERVAL_MS = 60000;
export const DEFAULT_LIVENESS_CHECK_RISK_AGE_SECONDS = 60;

export const LIVENESS_CHECK_INTERVAL_MS_ENV = 'LIVENESS_CHECK_INTERVAL_MS';
export const LIVENESS_CHECK_RISK_AGE_SECONDS_ENV =
  'LIVENESS_CHECK_RISK_AGE_SECONDS';
