export const GUARDIAN_NOTIFICATION_QUEUE = 'guardian-notification';
export const GUARDIAN_NOTIFICATION_DISPATCH_JOB_NAME = 'dispatch';
export const GUARDIAN_NOTIFICATION_NEGATIVE_RESPONSE_JOB_NAME =
  'negative-response';
export const DEFAULT_GUARDIAN_NOTIFICATION_INTERVAL_MS = 60000;
export const DEFAULT_GUARDIAN_NOTIFICATION_RISK_AGE_SECONDS = 60;
export const DEFAULT_GUARDIAN_NOTIFICATION_COOLDOWN_SECONDS = 300;

export const GUARDIAN_NOTIFICATION_ENABLED_ENV =
  'GUARDIAN_NOTIFICATION_ENABLED';
export const GUARDIAN_NOTIFICATION_INTERVAL_MS_ENV =
  'GUARDIAN_NOTIFICATION_INTERVAL_MS';
export const GUARDIAN_NOTIFICATION_RISK_AGE_SECONDS_ENV =
  'GUARDIAN_NOTIFICATION_RISK_AGE_SECONDS';
export const GUARDIAN_NOTIFICATION_COOLDOWN_SECONDS_ENV =
  'GUARDIAN_NOTIFICATION_COOLDOWN_SECONDS';
