export const EARTHQUAKE_POLLING_QUEUE = 'earthquake-polling';
export const EARTHQUAKE_POLLING_JOB_NAME = 'poll';

export const DEFAULT_EARTHQUAKE_POLLING_INTERVAL_MS = 300_000;
export const EARTHQUAKE_POLLING_INTERVAL_MS_ENV =
  'EARTHQUAKE_POLLING_INTERVAL_MS';
export const EARTHQUAKE_POLLING_ENABLED_ENV = 'EARTHQUAKE_POLLING_ENABLED';

export const DEFAULT_EARTHQUAKE_AFFECTED_RADIUS_KM = 200;
export const EARTHQUAKE_AFFECTED_RADIUS_KM_ENV =
  'EARTHQUAKE_AFFECTED_RADIUS_KM';

export const EARTHQUAKE_HIGH_RISK_MIN_MAGNITUDE = 5.5;
export const EARTHQUAKE_BROADCAST_MAGNITUDE_THRESHOLD = 6.0;
export const EARTHQUAKE_CRITICAL_MAGNITUDE_THRESHOLD = 6.5;
