export const ACCIDENT_MONITOR_QUEUE = 'accident-monitor';
export const ACCIDENT_MONITOR_JOB_NAME = 'monitor';

export const DEFAULT_ACCIDENT_MONITOR_INTERVAL_MS = 300_000;
export const ACCIDENT_MONITOR_INTERVAL_MS_ENV = 'ACCIDENT_MONITOR_INTERVAL_MS';
export const ACCIDENT_MONITOR_ENABLED_ENV = 'ACCIDENT_MONITOR_ENABLED';

export const DEFAULT_ACCIDENT_NO_MOVEMENT_HOURS = 6;
export const ACCIDENT_NO_MOVEMENT_HOURS_ENV = 'ACCIDENT_NO_MOVEMENT_HOURS';
